/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package turing.machine;

public class App {

    public static void main(String[] args) {
        TuringMachine turing = new TuringMachine("01010110101001#101010");
        turing.multiplication();
        turing.run();
    }
}