/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package turing.machine;

public class App {

    public static void main(String[] args) {
        TuringMachine turing = new TuringMachine("111_11"); //
        turing.run();
    }
}